#### DataSource ####
spring.datasource.url=jdbc:mysql://localhost:3306/parser?useSSL=false&serverTimezone=UTC
spring.datasource.username=root
spring.datasource.password=
spring.jpa.hibernate.ddl-auto=update

#### Batch ####
spring.batch.job.enabled=false
spring.batch.initialize-schema=always

#### Logging ####
logging.level.root=error
logging.level.org.springframework=off
logging.level.org.hibernate=error

#### Date Format Values ####
#DB-Format=yyyy-MM-dd HH:mm:ss.SSS
#Console-Format=yyyy-MM-dd.HH:mm:ss

accesslog=src/main/resources/access.log